CREATE OR REPLACE TABLE metrics.metric_catalog (
    metric_name VARCHAR,
    business_question VARCHAR,
    grain VARCHAR,
    formula VARCHAR,
    numerator VARCHAR,
    denominator VARCHAR,
    unit VARCHAR,
    filters VARCHAR,
    zero_null_rule VARCHAR,
    quality_and_boundary VARCHAR
);

INSERT INTO metrics.metric_catalog VALUES
('order_count', '运营日履约需求规模是多少', 'dt/整体', 'count(order)', '订单行数', '不适用', '订单', '订单事实；时间顺序质量标记为真时不入指标层', '无行则为0', 'dt为运营归属日；不代表自然下单日'),
('waybill_acceptance_rate', '派出的waybill有多少被接受', 'waybill dt/整体', 'accepted_waybill_count / waybill_attempt_count', '接受waybill数', '全部waybill尝试数', '比例', '排除时间顺序异常尝试', '分母0则NULL', '尝试粒度，不等于订单完成率'),
('first_attempt_success_rate', '订单能否在第一次尝试即被接受', '订单dt/整体', 'attempt_count=1订单数 / 订单数', '仅1次尝试订单数', '订单数', '比例', '订单指标层有效记录', '分母0则NULL', '第一次尝试由dispatch_time排序确定'),
('first_dispatch_success_rate', '首次派单是否成功', '订单dt/整体', '首次waybill被接受订单数 / 订单数', '仅1次尝试订单数', '订单数', '比例', '订单指标层有效记录', '分母0则NULL', '当前数据以waybill表示派单尝试，因此与first_attempt_success_rate恒等'),
('avg_attempt_count', '每单平均经历多少次分配尝试', '订单dt/整体', 'sum(attempt_count) / order_count', '尝试次数合计', '订单数', '次/订单', '订单指标层有效记录', '分母0则NULL', '含最终接受尝试'),
('avg_redispatch_count', '每单平均重派多少次', '订单dt/整体', 'sum(attempt_count-1) / order_count', '重派次数合计', '订单数', '次/订单', '订单指标层有效记录', '分母0则NULL', '首次尝试不算重派'),
('completion_rate', '已接受订单中有多少完成送达', '订单dt/整体', 'completed_order_count / order_count', 'arrive_time非0订单数', '已接受订单数', '比例', '订单事实', 'arrive_time=0记未完成；分母0则NULL', '1条未完成保留在分母，不进入完成时长'),
('avg_order_to_push_seconds', '下单后多久进入派单池', '订单dt/整体', 'sum(first_push-platform_order) / 有效订单数', '有效时长秒数合计', '两端时间存在且非负订单数', '秒', '排除时间顺序异常', '事件不存在则NULL且不入分母', '平台下单属性取最终接受waybill'),
('avg_push_to_first_dispatch_seconds', '入池后多久首次派单', '订单dt/整体', 'sum(first_dispatch-first_push) / 有效订单数', '有效时长秒数合计', '两端时间存在且非负订单数', '秒', '排除时间顺序异常', '0派单时间转NULL且不入分母', '首次派单取该订单最早非0 dispatch_time'),
('avg_first_dispatch_to_accept_seconds', '从首次派单到最终接单耗时多久', '订单dt/整体', 'sum(accept-first_dispatch) / 有效订单数', '有效时长秒数合计', '两端时间存在且非负订单数', '秒', '排除时间顺序异常', '缺失则NULL且不入分母', '包含拒绝与重派等待'),
('avg_final_dispatch_to_accept_seconds', '最终一次派单到接单耗时多久', '订单dt/整体', 'sum(accept-final_dispatch) / 有效订单数', '有效时长秒数合计', '两端时间存在且非负订单数', '秒', '排除时间顺序异常', '最终派单为0则NULL且不入分母', '标准派单至接单段；不含此前拒绝等待'),
('avg_accept_to_fetch_seconds', '接单后多久取餐', '订单dt/整体', 'sum(fetch-accept) / 有效订单数', '有效时长秒数合计', '两端时间存在且非负订单数', '秒', '排除时间顺序异常', '缺失则NULL且不入分母', '已接受订单'),
('avg_fetch_to_arrive_seconds', '取餐后多久送达', '订单dt/整体', 'sum(arrive-fetch) / 完成订单数', '有效时长秒数合计', '取餐和送达存在且非负订单数', '秒', '仅完成且顺序合法订单', '未完成为NULL并排除分母', '不静默纳入1条未完成记录'),
('avg_end_to_end_seconds', '下单到送达全链路多久', '订单dt/整体', 'sum(arrive-platform_order) / 完成订单数', '有效时长秒数合计', '下单和送达存在且非负订单数', '秒', '仅完成且顺序合法订单', '未完成为NULL并排除分母', '预订单可跨自然日，仍归属dt'),
('strict_late_rate', '实际送达是否超过承诺时刻', '订单dt/整体', 'arrive>estimate_arrived完成订单数 / 完成订单数', '严格超时完成订单数', '完成订单数', '比例', '仅完成订单', '未完成排除；分母0则NULL', '不对承诺时刻加缓冲'),
('buffer_8m_late_rate', '加入8分钟缓冲后仍超时多少', '订单dt/整体', 'arrive>estimate_arrived+480完成订单数 / 完成订单数', '缓冲超时完成订单数', '完成订单数', '比例', '仅完成订单', '未完成排除；分母0则NULL', '8分钟为显式业务缓冲，不替代严格口径'),
('avg_pickup_delay_seconds', '取餐相对预计出餐晚多久', '订单dt/整体', 'sum(fetch-estimated_meal_ready) / 有效订单数', '取餐延迟秒数合计', '预计出餐非0且取餐存在订单数', '秒', '预计出餐时间非0', '负值保留表示提前；缺失排除', '不是商户因果责任判断'),
('avg_delivery_distance_coordinate_units', '取送点直线距离如何变化', '订单dt/整体', '匿名坐标欧氏距离均值', '距离合计', '坐标可计算订单数', '匿名坐标单位', '订单指标层有效记录', '缺失则排除', '未知比例尺，禁止解释为公里或路网距离'),
('avg_wave_duration_seconds', '骑手波次平均持续多久', '波次dt/整体', 'sum(official_end-reconstructed_start) / 有效波次数', '合法波次时长秒数合计', '成员完整且时长非负波次数', '秒', '成员解析与关联完整', '非法或缺失时长排除', '开始时间必须使用成员最早有效grab_time重构'),
('avg_orders_per_wave', '每波平均承载多少订单', '波次dt/整体', 'sum(member_count) / wave_count', '波次成员数合计', '有效波次数', '订单/波', '成员解析与关联完整', '分母0则NULL', '成员数是订单负载代理'),
('p90_wave_load_orders', '高负载波次的订单数水平是多少', '波次dt', 'member_count的P90', '不适用', '有效波次分布', '订单/波', '成员解析与关联完整', '无波次则NULL', '描述性负载，不是异常阈值'),
('checkpoint_pending_order_count', '选定checkpoint待派订单有多少', 'dt+dispatch_time', 'count(checkpoint order members)', '待派订单成员数', '不适用', '订单', '订单侧快照存在', '缺侧则NULL并标记', '仅24个checkpoint，不能代表全天日志'),
('checkpoint_candidate_courier_count', '选定checkpoint候选骑手有多少', 'dt+dispatch_time', 'count(checkpoint rider members)', '候选骑手成员数', '不适用', '骑手', '骑手侧快照存在', '缺侧则NULL并标记', '仅24个checkpoint；不公开成员'),
('checkpoint_pending_orders_per_candidate_courier', 'checkpoint每名候选骑手对应多少待派订单', 'dt+dispatch_time', 'pending_order_count / candidate_courier_count', '待派订单数', '候选骑手数', '订单/骑手', '两侧快照均存在', '候选骑手为0则NULL', 'courier_waybills定义仍不确定；比值仅描述选定快照'),
('checkpoint_candidate_couriers_per_pending_order', 'checkpoint候选骑手订单比是多少', 'dt+dispatch_time', 'candidate_courier_count / pending_order_count', '候选骑手数', '待派订单数', '骑手/订单', '两侧快照均存在', '待派订单为0则NULL', '按中文字段顺序定义的候选骑手订单比；仅描述24个选定快照');
